stages:
 - build

Ubuntu-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export BUILD_GENERATOR="Ninja";
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

OSX-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load Qt-5.9.1
  - export BUILD_GENERATOR="Ninja";
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx-sierra

Win7-Subproject:
  stage: build
  script:
  - call %ENVFILESDIR%\Boost-1.64-vs14-x64.bat
  - call %ENVFILESDIR%\Qt-5.9-vs14.bat
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set GENERATOR_EXTRA_OPTIONS=
  - '"c:\Program Files\Git\bin\bash.exe" --login  .gitlab-ci.sh'
  tags:
  - win7
  except:
  - tags
