stages:
 - build

Ubuntu-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export BUILD_GENERATOR="Ninja";
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

OSX-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load Qt-5.4
  - export BUILD_GENERATOR="Ninja";
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx

Win7-Subproject:
  stage: build
  script:
  - call %ENVFILESDIR%\Qt-5.4.bat
  - call %ENVFILESDIR%\Boost-1.56-vs12-x64.bat
  - set BUILD_GENERATOR=Visual Studio 12 Win64
  - set GENERATOR_EXTRA_OPTIONS=
  - '"c:\Program Files (x86)\Git\bin\bash.exe" --login  .gitlab-ci.sh'
  - set PATH=%PATH%;"c:\Program Files (x86)\Git\bin"
  tags:
  - win7
  except:
  - tags
